En el local funciona no se por que en actions no

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -92,17 +92,17 @@ jobs:
 
       - name: OPA Policy Compliance Check
         run: |
-          RESULT_ANALYSIS=$(opa eval -i tfplan.json -d . "data.terraform.analysis.violation" --format json || echo "ERROR_OPA")
-          if [ "$RESULT_ANALYSIS" == "ERROR_OPA" ]; then echo "Error de ejecución en OPA Analysis"; exit 1; fi
-          echo "$RESULT_ANALYSIS" | grep -q '\[\]' || (echo "ERROR: Violación de política detectada (Tipo de instancia o Tags)." && exit 1)
+          RESULT_ANALYSIS=$(opa eval -i tfplan.json -d instancias.rego "data.terraform.analysis.violation" --format json || echo "ERROR_OPA")
+          if [ "$RESULT_ANALYSIS" == "ERROR_OPA" ]; then exit 1; fi
+          echo "$RESULT_ANALYSIS" | grep -q '\[\]' || exit 1
 
-          RESULT_NAME=$(opa eval -i tfplan.json -d . "data.terraform.authz.allow" --format json || echo "ERROR_OPA")
-          if [ "$RESULT_NAME" == "ERROR_OPA" ]; then echo "Error de ejecución en OPA Authz"; exit 1; fi
-          echo "$RESULT_NAME" | grep -q '"status":true' || (echo "ERROR: El nombre de la instancia no cumple la nomenclatura." && exit 1)
+          RESULT_NAME=$(opa eval -i tfplan.json -d authz.rego "data.terraform.authz.allow" --format json || echo "ERROR_OPA")
+          if [ "$RESULT_NAME" == "ERROR_OPA" ]; then exit 1; fi
+          echo "$RESULT_NAME" | grep -q '"status":true' || exit 1
 
-          RESULT_REGION=$(opa eval -i tfplan.json -d . "data.terraform_region_check.allow" --format json || echo "ERROR_OPA")
-          if [ "$RESULT_REGION" == "ERROR_OPA" ]; then echo "Error de ejecución en OPA Region"; exit 1; fi
-          echo "$RESULT_REGION" | grep -q 'true' || (echo "ERROR: La región configurada no es us-east-1." && exit 1)
+          RESULT_REGION=$(opa eval -i tfplan.json -d region.rego "data.terraform_region_check.allow" --format json || echo "ERROR_OPA")
+          if [ "$RESULT_REGION" == "ERROR_OPA" ]; then exit 1; fi
+          echo "$RESULT_REGION" | grep -q 'true' || exit 1
 
       - name: Upload Plan Artifact
         uses: actions/upload-artifact@v4
